"""db update

Revision ID: 432fbeebfb23
Revises: ffbc47b8aede
Create Date: 2021-07-09 00:34:25.579369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432fbeebfb23'
down_revision = 'ffbc47b8aede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deadline')
    op.drop_column('project', 'deadline')
    # ### end Alembic commands ###
